name: Security Scans
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install -r requirements.txt
      - name: Run Dependency Check (SCA)
        run: |
          pip install safety
          safety check --full-report > dependency-check-report.txt || true
      - name: Upload Dependency Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.txt